---
# Deploy three tier app

- name: Base Configuration
  hosts: all
  gather_facts: true
  become: true
  roles:
    - base-config

- name: Deploy haproxy
  hosts: tag_AnsibleGroup_frontends
  become: true
  roles:
    - haproxy

- name: Deploy Tomcat
  hosts: tag_AnsibleGroup_apps
  become: true
  roles:
    - tomcat

- name: Deploy PostgreSQL
  hosts: tag_AnsibleGroup_appdbs
  become: true
  roles:
    - patch-sudoers
    - geerlingguy.postgresql
