---
# Playbook to provision instances on osp
# Trying to remove the localhost option

- hosts: jumpbox
  become: yes
  roles:
    - osp-facts

- hosts: frontends
  gather_facts: false
  become: yes
  roles:
  - haproxy
