---
# Playbook to smoke test frontend on osp

- hosts: jumpbox
  gather_facts: false
  become: yes
  tasks:
  - name: Sleep before trying to run the osp smoke test
    pause:
      minutes: 1
  
  - name: OpenStack frontend servers
    os_server_facts:
      cloud: ospcloud
      server: 'frontend'
    register: result

  - name: Check that you can curl the frontends
    uri:
      url: "http://{{ item.public_v4 }}"
      return_content: yes
    with_items:
      - "{{ result.ansible_facts.openstack_servers }}"
    register: webpage

  - name: Fail if status not 200
    fail:
      msg: "Curl returned status code: item.status"
    when: item.status != 200
    with_items:
    - "{{ webpage.results }}"

  - name: Fail if 'Ansible has done its job' is not in the page content
    fail:
      msg: "Curl string not in result"
    when: "'Ansible has done its job' not in webpage.results[0].content"
