---
# Playbook to provision instances on osp
# Trying to remove the localhost option

- hosts: jumpbox
  become: yes
  roles:
    - osp-facts

- hosts: apps
  gather_facts: false
  tasks:
  - ping:

- hosts: frontends
  gather_facts: false
  tasks:
  - ping:

- hosts: appdbs
  gather_facts: false
  tasks:
  - ping:
 