---
# Playbook to provision instances on osp

- hosts: jumpbox
  vars:
    OSP_GUID: 9911
  become: yes
  roles:
    - osp-facts

- hosts: apps
  gather_facts: false
  tasks:
  - ping:
 
- hosts: frontends
  gather_facts: false
  tasks:
  - ping:
 
- hosts: appdbs
  gather_facts: false
  tasks:
  - ping:
 