---
# tasks file for osp-delete-instances

- name: OpenStack servers
  os_server_facts:
    cloud: ospcloud
  register: result
  
- name: Create server instances
  os_server:
    cloud: ospcloud
    name: "{{ item.name }}"
    state: absent
  with_items: "{{ result.ansible_facts.openstack_servers }}"
  register: instance_out
